/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TooltipAssignment {
        "text": string;
    }
}
declare global {
    interface HTMLTooltipAssignmentElement extends Components.TooltipAssignment, HTMLStencilElement {
    }
    var HTMLTooltipAssignmentElement: {
        prototype: HTMLTooltipAssignmentElement;
        new (): HTMLTooltipAssignmentElement;
    };
    interface HTMLElementTagNameMap {
        "tooltip-assignment": HTMLTooltipAssignmentElement;
    }
}
declare namespace LocalJSX {
    interface TooltipAssignment {
        "text"?: string;
    }
    interface IntrinsicElements {
        "tooltip-assignment": TooltipAssignment;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tooltip-assignment": LocalJSX.TooltipAssignment & JSXBase.HTMLAttributes<HTMLTooltipAssignmentElement>;
        }
    }
}
